package enums;

public enum JunoErrorType {
    TODO_ERROR, DEADLINE_ERROR, EVENT_ERROR, LIST_ERROR,
    MARK_ERROR, UNMARK_ERROR, DELETE_ERROR, LOAD_ERROR,
    INVALID_FORMAT_ERROR, INVALID_TYPE_ERROR, LIST_WITH_DATE_ERROR;
}