package juno.enums;

public enum ErrorType {
    CREATE_FILE_ERROR, DATE_ERROR, DEADLINE_ERROR, DELETE_ERROR,
    EVENT_ERROR, INVALID_FORMAT_ERROR, INVALID_TYPE_ERROR, LIST_ERROR,
    LIST_WITH_DATE_ERROR, LOAD_ERROR, MARK_ERROR,
    READ_FILE_ERROR, TASK_ERROR, TODO_ERROR, UNMARK_ERROR
}
